# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 298f1c5a3e299e0d8c411c9b3667e740f8818088c85ae832208f862de1f0d35dcec7d035f9dbaa85551848dbeff0e1ae4a72cabf2b8d1ecd7faa69a2c1d9895e

test:
  secret_key_base: c6290cf6d52bbe187386597133162d8ae3c9ee858b7086c0d8b533c513fedf14530b0ed4316ea88a5e50d2db2b9a4189d92bee2a90894cae4a09558c959a12e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
